name: Generate Diagrams from StarUML MDJ

on:
  push:
    branches:
      - main
    paths:
      - '**.mdj'

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

      - name: Install StarUML CLI
        run: |
          # Download StarUML CLI instead of using mdgen
          mkdir -p ./staruml-cli
          cd ./staruml-cli
          wget https://github.com/staruml/staruml-cli/releases/latest/download/staruml-cli-linux-x64.tar.gz
          tar -xzf staruml-cli-linux-x64.tar.gz
          sudo chmod +x ./staruml

      - name: Generate Diagrams from MDJ
        run: |
          find . -name "*.mdj" | while read mdj_file; do
            output_dir="diagrams/$(dirname "${mdj_file#./}")"
            mkdir -p "$output_dir"
            
            # Export diagrams as PNG using StarUML CLI
            ./staruml-cli/staruml export --format png "$mdj_file" --out "$output_dir"
            
            # Rename files to match diagram names if needed
            # This might need customization based on how StarUML CLI names the output files
          done

      - name: Commit and Push Generated Diagrams
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add diagrams/
          git commit -m "Generate diagrams from StarUML MDJ files" || echo "No changes to commit"
          git push 